# 가설4 
시험폐지 후 창체활동이 늘었을까? -> 창체 4가지 활동 중 동아리 활동 현황 분석
## 창체활동-동아리 가입 증가수 데이터전처리
### 변수설정
- df_club# : 2012년부터 2018년까지 동아리가입 df-오름차순 (예. df_club1= 2012년도 동아리가입현황)
- raw : 전처리 완료 된 df
- sex : 남/여 성별 df
- elementary : 초등 df
- mid : 중등 df
- high :고등 df
- region : 지역규모분류별 df
- familytype : 가정유형형태 df
- economic : 경제수준별 df

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import koreanize_matplotlib
import datetime as dt
from dateutil.parser import parse

/Users/jahyeon_gu/.pyenv/versions/anaconda3-2022.05/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
from glob import glob
file_names= glob("미니&미드플젝 data/동아리*")
file_names

['미니&미드플젝 data\\동아리_가입_및_활동_여부_2012.csv',
 '미니&미드플젝 data\\동아리_가입_및_활동_여부_2013.csv',
 '미니&미드플젝 data\\동아리_가입_및_활동_여부_2014.csv',
 '미니&미드플젝 data\\동아리_가입_및_활동_여부_2015.csv',
 '미니&미드플젝 data\\동아리_가입_및_활동_여부_2016.csv',
 '미니&미드플젝 data\\동아리_가입_및_활동_여부_2017_2018.csv']

In [3]:
#컬럼 디스플레이 최대로 보이기
pd.options.display.max_columns = None

In [3]:
df_club1 = pd.read_csv('./dataset/동아리_가입_및_활동_여부_2017_2018.csv', encoding="cp949")
df_club1.head()

FileNotFoundError: [Errno 2] No such file or directory: '미니&미드플젝 data\\동아리_가입_및_활동_여부_2017_2018.csv'

In [4]:
df_club1 = pd.read_csv(file_names[0],encoding="cp949")
df_club1

,응답자유형별(1),응답자유형별(2),2012,2012.1,2012.2,2012.3,2012.4,2012.5
0,응답자유형별(1),응답자유형별(2),전체(N),전체(N),있다,있다,없다,없다
1,응답자유형별(1),응답자유형별(2),응답자수 (명),응답률 (%),응답자수 (명),응답률 (%),응답자수 (명),응답률 (%)
2,전체,소계,9075,100.0,4829,53.2,4246,46.8
3,성별,남자,4766,100.0,2486,52.2,2280,47.8
4,성별,여자,4309,100.0,2343,54.4,1966,45.6
5,학교유형별,초등학교,2812,100.0,1339,47.6,1472,52.4
6,학교유형별,중학교,3106,100.0,1801,58.0,1305,42.0
7,학교유형별,일반계고,2429,100.0,1344,55.3,1085,44.7
8,학교유형별,전문계고,728,100.0,344,47.3,384,52.7
9,지역규모별,대도시,3949,100.0,2118,53.6,1831,46.4
10,지역규모별,중소도시,3839,100.0,2017,52.5,1822,47.5
11,지역규모별,읍/면,1287,100.0,694,54.0,593,46.0
12,가족유형별,양부모가정,7995,100.0,4323,54.1,3671,45.9
13,가족유형별,한부모가정,773,100.0,367,47.4,406,52.6
14,가족유형별,조손가정,108,100.0,56,51.7,52,48.3
15,가족유형별,기타,113,100.0,48,42.8,65,57.2
16,경제적수준별,상,1271,100.0,724,57.0,547,43.0
17,경제적수준별,중,7262,100.0,3830,52.7,3432,47.3
18,경제적수준별,하,490,100.0,255,51.9,236,48.1

In [5]:
#정렬 함수 생성
list=[]
def sortted(df):
#     df.column=list
    df=df.loc[1:]
    df=df.drop([15,16,17])
    df=df.reset_index(drop=True)
    return df

In [6]:
# 있다/없다 응답률 만 빼고컬럼 삭제
df_club1= df_club1.drop(columns=['2012','2012.1','2012.2','2012.4'])
df_club1

    응답자유형별(1)  응답자유형별(2)   2012.3   2012.5
0   응답자유형별(1)  응답자유형별(2)       있다       없다
1   응답자유형별(1)  응답자유형별(2)  응답률 (%)  응답률 (%)
2          전체         소계     53.2     46.8
3          성별         남자     52.2     47.8
4          성별         여자     54.4     45.6
5       학교유형별       초등학교     47.6     52.4
6       학교유형별        중학교     58.0     42.0
7       학교유형별       일반계고     55.3     44.7
8       학교유형별       전문계고     47.3     52.7
9       지역규모별        대도시     53.6     46.4
10      지역규모별       중소도시     52.5     47.5
11      지역규모별        읍/면     54.0     46.0
12      가족유형별      양부모가정     54.1     45.9
13      가족유형별      한부모가정     47.4     52.6
14      가족유형별       조손가정     51.7     48.3
15      가족유형별         기타     42.8     57.2
16     경제적수준별          상     57.0     43.0
17     경제적수준별          중     52.7     47.3
18     경제적수준별          하     51.9     48.1

In [7]:
#3,4 컬럼명 바꾸기
df_club1.columns=['응답자유형별(1)', '응답자유형별(2)', '2012 있다(%)', '2012 없다(%)']
#불필요한 row 없애기 멀티인덱스자료라 컬럼명이 중복으로 표기되어있음
df_club1=df_club1.loc[2:]
#인덱스 재정렬
df_club1=df_club1.reset_index(drop=True)
df_club1

   응답자유형별(1) 응답자유형별(2) 2012 있다(%) 2012 없다(%)
0         전체        소계       53.2       46.8
1         성별        남자       52.2       47.8
2         성별        여자       54.4       45.6
3      학교유형별      초등학교       47.6       52.4
4      학교유형별       중학교       58.0       42.0
5      학교유형별      일반계고       55.3       44.7
6      학교유형별      전문계고       47.3       52.7
7      지역규모별       대도시       53.6       46.4
8      지역규모별      중소도시       52.5       47.5
9      지역규모별       읍/면       54.0       46.0
10     가족유형별     양부모가정       54.1       45.9
11     가족유형별     한부모가정       47.4       52.6
12     가족유형별      조손가정       51.7       48.3
13     가족유형별        기타       42.8       57.2
14    경제적수준별         상       57.0       43.0
15    경제적수준별         중       52.7       47.3
16    경제적수준별         하       51.9       48.1

In [8]:
df_club1=df_club1.replace(" ","")

In [9]:
df_club2 = pd.read_csv(file_names[1],encoding="cp949")
df_club2

    응답자유형별(1)  응답자유형별(2)  2013 2013.1
0   응답자유형별(1)  응답자유형별(2)    있다     없다
1          전체         소계  70.9   29.1
2          성별         남자  69.7   30.3
3          성별         여자  72.2   27.8
4       학교유형별       초등학교  67.5   32.5
5       학교유형별        중학교  73.1   26.9
6       학교유형별  일반/특목/자율고  73.1   26.9
7       학교유형별       특성화고  64.4   35.6
8       지역규모별        대도시  72.7   27.3
9       지역규모별       중소도시  67.4   32.6
10      지역규모별       읍면지역  77.5   22.5
11      가족유형별      양부모가정  71.2   28.8
12      가족유형별      한부모가정  68.3   31.7
13      가족유형별       조손가정  75.8   24.2
14      가족유형별         기타  61.7   38.3
15      학업성적별          상  73.8   26.2
16      학업성적별          중  69.9   30.1
17      학업성적별          하  69.3   30.7
18     경제적수준별          상  72.7   27.3
19     경제적수준별          중  68.9   31.1
20     경제적수준별          하  70.5   29.5

In [10]:
df_club2=sortted(df_club2)
df_club2.columns=['응답자유형별(1)', '응답자유형별(2)', '2013 있다(%)', '2013 없다(%)']
# df_club2

In [12]:
df_club2=df_club2.replace(" ","")

In [13]:
df_club3 = pd.read_csv(file_names[2],encoding="cp949")
df_club3

    응답자유형별(1)  응답자유형별(2)  2014 2014.1
0   응답자유형별(1)  응답자유형별(2)    있다     없다
1          전체         소계  74.6   25.4
2          성별         남자  74.4   25.6
3          성별         여자  74.9   25.1
4       학교유형별       초등학교  74.6   25.4
5       학교유형별        중학교  75.5   24.5
6       학교유형별  일반/특목/자율고  73.7   26.3
7       학교유형별       특성화고  74.3   25.7
8       지역규모별        대도시  76.8   23.2
9       지역규모별       중소도시  72.3   27.7
10      지역규모별       읍면지역  75.7   24.3
11      가족유형별      양부모가정  75.0   25.0
12      가족유형별      한부모가정  68.5   31.5
13      가족유형별       조손가정  76.4   23.6
14      가족유형별         기타  69.3   30.7
15      학업성적별          상  79.7   20.3
16      학업성적별          중  74.3   25.7
17      학업성적별          하  69.5   30.5
18     경제적수준별          상  76.9   23.1
19     경제적수준별          중  73.1   26.9
20     경제적수준별          하  72.3   27.7

In [14]:
df_club3=sortted(df_club3)

In [15]:
df_club3.columns=['응답자유형별(1)', '응답자유형별(2)', '2014 있다(%)', '2014 없다(%)']
df_club3

   응답자유형별(1)  응답자유형별(2) 2014 있다(%) 2014 없다(%)
0         전체         소계       74.6       25.4
1         성별         남자       74.4       25.6
2         성별         여자       74.9       25.1
3      학교유형별       초등학교       74.6       25.4
4      학교유형별        중학교       75.5       24.5
5      학교유형별  일반/특목/자율고       73.7       26.3
6      학교유형별       특성화고       74.3       25.7
7      지역규모별        대도시       76.8       23.2
8      지역규모별       중소도시       72.3       27.7
9      지역규모별       읍면지역       75.7       24.3
10     가족유형별      양부모가정       75.0       25.0
11     가족유형별      한부모가정       68.5       31.5
12     가족유형별       조손가정       76.4       23.6
13     가족유형별         기타       69.3       30.7
14    경제적수준별          상       76.9       23.1
15    경제적수준별          중       73.1       26.9
16    경제적수준별          하       72.3       27.7

In [16]:
df_club4 = pd.read_csv(file_names[3],encoding="cp949")
df_club4

    응답자유형별(1)  응답자유형별(2)  2015 2015.1
0   응답자유형별(1)  응답자유형별(2)    있다     없다
1          전체         소계  72.6   27.4
2          성별         남자  72.0   28.0
3          성별         여자  73.2   26.8
4       학교유형별       초등학교  71.3   28.7
5       학교유형별        중학교  72.3   27.7
6       학교유형별  일반/특목/자율고  73.5   26.5
7       학교유형별       특성화고  75.0   25.0
8       지역규모별        대도시  77.5   22.5
9       지역규모별       중소도시  67.3   32.7
10      지역규모별       읍면지역  72.4   27.6
11      가족유형별      양부모가정  72.9   27.1
12      가족유형별      한부모가정  69.2   30.8
13      가족유형별       조손가정  73.9   26.1
14      가족유형별         기타  61.0   39.0
15      학업성적별          상  77.4   22.6
16      학업성적별          중  71.5   28.5
17      학업성적별          하  67.9   32.1
18     경제적수준별          상  74.7   25.3
19     경제적수준별          중  70.2   29.8
20     경제적수준별          하  70.4   29.6

In [17]:
df_club4=sortted(df_club4)
df_club4.columns=['응답자유형별(1)', '응답자유형별(2)', '2015 있다(%)', '2015 없다(%)']
df_club4

   응답자유형별(1)  응답자유형별(2) 2015 있다(%) 2015 없다(%)
0         전체         소계       72.6       27.4
1         성별         남자       72.0       28.0
2         성별         여자       73.2       26.8
3      학교유형별       초등학교       71.3       28.7
4      학교유형별        중학교       72.3       27.7
5      학교유형별  일반/특목/자율고       73.5       26.5
6      학교유형별       특성화고       75.0       25.0
7      지역규모별        대도시       77.5       22.5
8      지역규모별       중소도시       67.3       32.7
9      지역규모별       읍면지역       72.4       27.6
10     가족유형별      양부모가정       72.9       27.1
11     가족유형별      한부모가정       69.2       30.8
12     가족유형별       조손가정       73.9       26.1
13     가족유형별         기타       61.0       39.0
14    경제적수준별          상       74.7       25.3
15    경제적수준별          중       70.2       29.8
16    경제적수준별          하       70.4       29.6

In [18]:
df_club4=df_club4.replace(" ","")

In [19]:
df_club5 = pd.read_csv(file_names[4],encoding="cp949")
df_club5

    응답자유형별(1)  응답자유형별(2)  2016 2016.1
0   응답자유형별(1)  응답자유형별(2)    있다     없다
1          전체         소계  73.6   26.4
2          성별         남자  72.5   27.5
3          성별         여자  74.8   25.2
4       학교유형별       초등학교    76     24
5       학교유형별        중학교  75.4   24.6
6       학교유형별       고등학교  70.2   29.8
7        고교유형       일반계고  70.6   29.4
8        고교유형      특성화계고  68.6   31.4
9       지역규모별        대도시  78.4   21.6
10      지역규모별       중소도시  70.3   29.7
11      지역규모별       읍면지역  70.7   29.3
12      가족유형별      양부모가정  73.7   26.3
13      가족유형별      한부모가정    73     27
14      가족유형별       조손가정  79.1   20.9
15      가족유형별         기타  67.5   32.5
16      학업성적별          상  77.1   22.9
17      학업성적별          중  74.7   25.3
18      학업성적별          하  67.2   32.8
19     경제적수준별          상  76.1   23.9
20     경제적수준별          중  70.6   29.4
21     경제적수준별          하  71.6   28.4

In [20]:
# df_club5=sortted(df_club5) => 행 수가 달라서 함수 쓸수가 없음..
df_club5=df_club5.loc[1:]
df_club5=df_club5.drop([16,17,18])
df_club5=df_club5.reset_index(drop=True)
df_club5.columns=['응답자유형별(1)', '응답자유형별(2)', '2016 있다(%)', '2016 없다(%)']
df_club5=df_club5.drop([5])
df_club5=df_club5.reset_index(drop=True)

In [21]:
df_club5

   응답자유형별(1) 응답자유형별(2) 2016 있다(%) 2016 없다(%)
0         전체        소계       73.6       26.4
1         성별        남자       72.5       27.5
2         성별        여자       74.8       25.2
3      학교유형별      초등학교         76         24
4      학교유형별       중학교       75.4       24.6
5       고교유형      일반계고       70.6       29.4
6       고교유형     특성화계고       68.6       31.4
7      지역규모별       대도시       78.4       21.6
8      지역규모별      중소도시       70.3       29.7
9      지역규모별      읍면지역       70.7       29.3
10     가족유형별     양부모가정       73.7       26.3
11     가족유형별     한부모가정         73         27
12     가족유형별      조손가정       79.1       20.9
13     가족유형별        기타       67.5       32.5
14    경제적수준별         상       76.1       23.9
15    경제적수준별         중       70.6       29.4
16    경제적수준별         하       71.6       28.4

In [22]:
df_club6 = pd.read_csv(file_names[5],encoding="cp949")
df_club6

    응답자유형별(1)  응답자유형별(2)  2017 2017.1  2018 2018.1
0   응답자유형별(1)  응답자유형별(2)    있다     없다    있다     없다
1          전체         소계  77.6   22.4  75.9   24.1
2          성별         남자  76.3   23.7  74.7   25.3
3          성별         여자  79.1   20.9  77.2   22.8
4         학교급       초등학교  80.3   19.7  76.5   23.5
5         학교급        중학교  76.2   23.8  75.0   25.0
6         학교급       고등학교  76.8   23.2  76.2   23.8
7        고교유형       일반계고  77.0   23.0  76.0   24.0
8        고교유형      특성화계고  75.6   24.4  77.1   22.9
9        지역규모        대도시  80.6   19.4  79.8   20.2
10       지역규모       중소도시  74.8   25.2  72.5   27.5
11       지역규모       읍면지역  77.4   22.6  76.5   23.5
12       가족유형      양부모가정  78.0   22.0  76.3   23.7
13       가족유형      한부모가정  76.4   23.6  71.4   28.6
14       가족유형       조손가정  75.1   24.9  80.0   20.0
15       가족유형         기타  59.6   40.4  69.2   30.8
16       학업성적          상  80.2   19.8  80.2   19.8
17       학업성적          중  77.9   22.1  74.9   25.1
18       학업성적          하  73.3   26.7  71.7   28.3
19     경제적 수준          상  78.5   21.5  77.2   22.8
20     경제적 수준          중  76.8   23.2  74.4   25.6
21     경제적 수준          하  75.6   24.4  73.9   26.1

In [23]:
df_club6=df_club6.loc[1:]
df_club6=df_club6.drop([16,17,18])
df_club6=df_club6.reset_index(drop=True)
df_club6.columns=['응답자유형별(1)', '응답자유형별(2)', '2017 있다(%)', '2017 없다(%)','2018 있다(%)', '2018 없다(%)']
df_club6

df_club6=df_club6.drop([5])
df_club6=df_club6.reset_index(drop=True)

In [24]:
df_club6

   응답자유형별(1) 응답자유형별(2) 2017 있다(%) 2017 없다(%) 2018 있다(%) 2018 없다(%)
0         전체        소계       77.6       22.4       75.9       24.1
1         성별        남자       76.3       23.7       74.7       25.3
2         성별        여자       79.1       20.9       77.2       22.8
3        학교급      초등학교       80.3       19.7       76.5       23.5
4        학교급       중학교       76.2       23.8       75.0       25.0
5       고교유형      일반계고       77.0       23.0       76.0       24.0
6       고교유형     특성화계고       75.6       24.4       77.1       22.9
7       지역규모       대도시       80.6       19.4       79.8       20.2
8       지역규모      중소도시       74.8       25.2       72.5       27.5
9       지역규모      읍면지역       77.4       22.6       76.5       23.5
10      가족유형     양부모가정       78.0       22.0       76.3       23.7
11      가족유형     한부모가정       76.4       23.6       71.4       28.6
12      가족유형      조손가정       75.1       24.9       80.0       20.0
13      가족유형        기타       59.6       40.4       69.2       30.8
14    경제적 수준         상       78.5       21.5       77.2       22.8
15    경제적 수준         중       76.8       23.2       74.4       25.6
16    경제적 수준         하       75.6       24.4       73.9       26.1

In [25]:
#연도별 df 합치기
result=pd.concat([df_club1,df_club2,df_club3,df_club4,df_club5,df_club6], axis=1)
result

,응답자유형별(1),응답자유형별(2),2012 있다(%),2012 없다(%),응답자유형별(1),응답자유형별(2),2013 있다(%),2013 없다(%),응답자유형별(1),응답자유형별(2),2014 있다(%),2014 없다(%),응답자유형별(1),응답자유형별(2),2015 있다(%),2015 없다(%),응답자유형별(1),응답자유형별(2),2016 있다(%),2016 없다(%),응답자유형별(1),응답자유형별(2),2017 있다(%),2017 없다(%),2018 있다(%),2018 없다(%)
0,전체,소계,53.2,46.8,전체,소계,70.9,29.1,전체,소계,74.6,25.4,전체,소계,72.6,27.4,전체,소계,73.6,26.4,전체,소계,77.6,22.4,75.9,24.1
1,성별,남자,52.2,47.8,성별,남자,69.7,30.3,성별,남자,74.4,25.6,성별,남자,72.0,28.0,성별,남자,72.5,27.5,성별,남자,76.3,23.7,74.7,25.3
2,성별,여자,54.4,45.6,성별,여자,72.2,27.8,성별,여자,74.9,25.1,성별,여자,73.2,26.8,성별,여자,74.8,25.2,성별,여자,79.1,20.9,77.2,22.8
3,학교유형별,초등학교,47.6,52.4,학교유형별,초등학교,67.5,32.5,학교유형별,초등학교,74.6,25.4,학교유형별,초등학교,71.3,28.7,학교유형별,초등학교,76,24,학교급,초등학교,80.3,19.7,76.5,23.5
4,학교유형별,중학교,58.0,42.0,학교유형별,중학교,73.1,26.9,학교유형별,중학교,75.5,24.5,학교유형별,중학교,72.3,27.7,학교유형별,중학교,75.4,24.6,학교급,중학교,76.2,23.8,75.0,25.0
5,학교유형별,일반계고,55.3,44.7,학교유형별,일반/특목/자율고,73.1,26.9,학교유형별,일반/특목/자율고,73.7,26.3,학교유형별,일반/특목/자율고,73.5,26.5,고교유형,일반계고,70.6,29.4,고교유형,일반계고,77.0,23.0,76.0,24.0
6,학교유형별,전문계고,47.3,52.7,학교유형별,특성화고,64.4,35.6,학교유형별,특성화고,74.3,25.7,학교유형별,특성화고,75.0,25.0,고교유형,특성화계고,68.6,31.4,고교유형,특성화계고,75.6,24.4,77.1,22.9
7,지역규모별,대도시,53.6,46.4,지역규모별,대도시,72.7,27.3,지역규모별,대도시,76.8,23.2,지역규모별,대도시,77.5,22.5,지역규모별,대도시,78.4,21.6,지역규모,대도시,80.6,19.4,79.8,20.2
8,지역규모별,중소도시,52.5,47.5,지역규모별,중소도시,67.4,32.6,지역규모별,중소도시,72.3,27.7,지역규모별,중소도시,67.3,32.7,지역규모별,중소도시,70.3,29.7,지역규모,중소도시,74.8,25.2,72.5,27.5
9,지역규모별,읍/면,54.0,46.0,지역규모별,읍면지역,77.5,22.5,지역규모별,읍면지역,75.7,24.3,지역규모별,읍면지역,72.4,27.6,지역규모별,읍면지역,70.7,29.3,지역규모,읍면지역,77.4,22.6,76.5,23.5
10,가족유형별,양부모가정,54.1,45.9,가족유형별,양부모가정,71.2,28.8,가족유형별,양부모가정,75.0,25.0,가족유형별,양부모가정,72.9,27.1,가족유형별,양부모가정,73.7,26.3,가족유형,양부모가정,78.0,22.0,76.3,23.7
11,가족유형별,한부모가정,47.4,52.6,가족유형별,한부모가정,68.3,31.7,가족유형별,한부모가정,68.5,31.5,가족유형별,한부모가정,69.2,30.8,가족유형별,한부모가정,73,27,가족유형,한부모가정,76.4,23.6,71.4,28.6
12,가족유형별,조손가정,51.7,48.3,가족유형별,조손가정,75.8,24.2,가족유형별,조손가정,76.4,23.6,가족유형별,조손가정,73.9,26.1,가족유형별,조손가정,79.1,20.9,가족유형,조손가정,75.1,24.9,80.0,20.0
13,가족유형별,기타,42.8,57.2,가족유형별,기타,61.7,38.3,가족유형별,기타,69.3,30.7,가족유형별,기타,61.0,39.0,가족유형별,기타,67.5,32.5,가족유형,기타,59.6,40.4,69.2,30.8
14,경제적수준별,상,57.0,43.0,경제적수준별,상,72.7,27.3,경제적수준별,상,76.9,23.1,경제적수준별,상,74.7,25.3,경제적수준별,상,76.1,23.9,경제적 수준,상,78.5,21.5,77.2,22.8
15,경제적수준별,중,52.7,47.3,경제적수준별,중,68.9,31.1,경제적수준별,중,73.1,26.9,경제적수준별,중,70.2,29.8,경제적수준별,중,70.6,29.4,경제적 수준,중,76.8,23.2,74.4,25.6
16,경제적수준별,하,51.9,48.1,경제적수준별,하,70.5,29.5,경제적수준별,하,72.3,27.7,경제적수준별,하,70.4,29.6,경제적수준별,하,71.6,28.4,경제적 수준,하,75.6,24.4,73.9,26.1

In [26]:
result.columns

Index(['응답자유형별(1)', '응답자유형별(2)', '2012 있다(%)', '2012 없다(%)', '응답자유형별(1)',
       '응답자유형별(2)', '2013 있다(%)', '2013 없다(%)', '응답자유형별(1)', '응답자유형별(2)',
       '2014 있다(%)', '2014 없다(%)', '응답자유형별(1)', '응답자유형별(2)', '2015 있다(%)',
       '2015 없다(%)', '응답자유형별(1)', '응답자유형별(2)', '2016 있다(%)', '2016 없다(%)',
       '응답자유형별(1)', '응답자유형별(2)', '2017 있다(%)', '2017 없다(%)', '2018 있다(%)',
       '2018 없다(%)'],
      dtype='object')

In [27]:
col=result[['응답자유형별(1)', '응답자유형별(2)','2012 있다(%)', '2012 없다(%)','2013 있다(%)', '2013 없다(%)','2014 있다(%)', '2014 없다(%)','2015 있다(%)','2015 없다(%)','2016 있다(%)', '2016 없다(%)','2017 있다(%)', '2017 없다(%)','2018 있다(%)',
       '2018 없다(%)']]

In [28]:
col.columns

Index(['응답자유형별(1)', '응답자유형별(1)', '응답자유형별(1)', '응답자유형별(1)', '응답자유형별(1)',
       '응답자유형별(1)', '응답자유형별(2)', '응답자유형별(2)', '응답자유형별(2)', '응답자유형별(2)',
       '응답자유형별(2)', '응답자유형별(2)', '2012 있다(%)', '2012 없다(%)', '2013 있다(%)',
       '2013 없다(%)', '2014 있다(%)', '2014 없다(%)', '2015 있다(%)', '2015 없다(%)',
       '2016 있다(%)', '2016 없다(%)', '2017 있다(%)', '2017 없다(%)', '2018 있다(%)',
       '2018 없다(%)'],
      dtype='object')

In [29]:
#전치행렬로 중복된 컬럼들 다 앞으로 빼기 
raw=col.T.drop_duplicates().T
raw

,응답자유형별(1),응답자유형별(1),응답자유형별(1),응답자유형별(2),응답자유형별(2),응답자유형별(2),2012 있다(%),2012 없다(%),2013 있다(%),2013 없다(%),2014 있다(%),2014 없다(%),2015 있다(%),2015 없다(%),2016 있다(%),2016 없다(%),2017 있다(%),2017 없다(%),2018 있다(%),2018 없다(%)
0,전체,전체,전체,소계,소계,소계,53.2,46.8,70.9,29.1,74.6,25.4,72.6,27.4,73.6,26.4,77.6,22.4,75.9,24.1
1,성별,성별,성별,남자,남자,남자,52.2,47.8,69.7,30.3,74.4,25.6,72.0,28.0,72.5,27.5,76.3,23.7,74.7,25.3
2,성별,성별,성별,여자,여자,여자,54.4,45.6,72.2,27.8,74.9,25.1,73.2,26.8,74.8,25.2,79.1,20.9,77.2,22.8
3,학교유형별,학교유형별,학교급,초등학교,초등학교,초등학교,47.6,52.4,67.5,32.5,74.6,25.4,71.3,28.7,76,24,80.3,19.7,76.5,23.5
4,학교유형별,학교유형별,학교급,중학교,중학교,중학교,58.0,42.0,73.1,26.9,75.5,24.5,72.3,27.7,75.4,24.6,76.2,23.8,75.0,25.0
5,학교유형별,고교유형,고교유형,일반계고,일반/특목/자율고,일반계고,55.3,44.7,73.1,26.9,73.7,26.3,73.5,26.5,70.6,29.4,77.0,23.0,76.0,24.0
6,학교유형별,고교유형,고교유형,전문계고,특성화고,특성화계고,47.3,52.7,64.4,35.6,74.3,25.7,75.0,25.0,68.6,31.4,75.6,24.4,77.1,22.9
7,지역규모별,지역규모별,지역규모,대도시,대도시,대도시,53.6,46.4,72.7,27.3,76.8,23.2,77.5,22.5,78.4,21.6,80.6,19.4,79.8,20.2
8,지역규모별,지역규모별,지역규모,중소도시,중소도시,중소도시,52.5,47.5,67.4,32.6,72.3,27.7,67.3,32.7,70.3,29.7,74.8,25.2,72.5,27.5
9,지역규모별,지역규모별,지역규모,읍/면,읍면지역,읍면지역,54.0,46.0,77.5,22.5,75.7,24.3,72.4,27.6,70.7,29.3,77.4,22.6,76.5,23.5
10,가족유형별,가족유형별,가족유형,양부모가정,양부모가정,양부모가정,54.1,45.9,71.2,28.8,75.0,25.0,72.9,27.1,73.7,26.3,78.0,22.0,76.3,23.7
11,가족유형별,가족유형별,가족유형,한부모가정,한부모가정,한부모가정,47.4,52.6,68.3,31.7,68.5,31.5,69.2,30.8,73,27,76.4,23.6,71.4,28.6
12,가족유형별,가족유형별,가족유형,조손가정,조손가정,조손가정,51.7,48.3,75.8,24.2,76.4,23.6,73.9,26.1,79.1,20.9,75.1,24.9,80.0,20.0
13,가족유형별,가족유형별,가족유형,기타,기타,기타,42.8,57.2,61.7,38.3,69.3,30.7,61.0,39.0,67.5,32.5,59.6,40.4,69.2,30.8
14,경제적수준별,경제적수준별,경제적 수준,상,상,상,57.0,43.0,72.7,27.3,76.9,23.1,74.7,25.3,76.1,23.9,78.5,21.5,77.2,22.8
15,경제적수준별,경제적수준별,경제적 수준,중,중,중,52.7,47.3,68.9,31.1,73.1,26.9,70.2,29.8,70.6,29.4,76.8,23.2,74.4,25.6
16,경제적수준별,경제적수준별,경제적 수준,하,하,하,51.9,48.1,70.5,29.5,72.3,27.7,70.4,29.6,71.6,28.4,75.6,24.4,73.9,26.1

In [31]:
raw=raw.replace('지역규모','지역규모별')
raw=raw.replace('가족유형','가족유형별')
raw=raw.replace('경제적 수준','경제적수준별')
raw=raw.replace('학교급','학교유형별')
raw=raw.replace('읍면지역','읍/면')
raw=raw.replace('가족유형','가족유형별')
raw

,응답자유형별(1),응답자유형별(1),응답자유형별(1),응답자유형별(2),응답자유형별(2),응답자유형별(2),2012 있다(%),2012 없다(%),2013 있다(%),2013 없다(%),2014 있다(%),2014 없다(%),2015 있다(%),2015 없다(%),2016 있다(%),2016 없다(%),2017 있다(%),2017 없다(%),2018 있다(%),2018 없다(%)
0,전체,전체,전체,소계,소계,소계,53.2,46.8,70.9,29.1,74.6,25.4,72.6,27.4,73.6,26.4,77.6,22.4,75.9,24.1
1,성별,성별,성별,남자,남자,남자,52.2,47.8,69.7,30.3,74.4,25.6,72.0,28.0,72.5,27.5,76.3,23.7,74.7,25.3
2,성별,성별,성별,여자,여자,여자,54.4,45.6,72.2,27.8,74.9,25.1,73.2,26.8,74.8,25.2,79.1,20.9,77.2,22.8
3,학교유형별,학교유형별,학교유형별,초등학교,초등학교,초등학교,47.6,52.4,67.5,32.5,74.6,25.4,71.3,28.7,76,24,80.3,19.7,76.5,23.5
4,학교유형별,학교유형별,학교유형별,중학교,중학교,중학교,58.0,42.0,73.1,26.9,75.5,24.5,72.3,27.7,75.4,24.6,76.2,23.8,75.0,25.0
5,학교유형별,고교유형,고교유형,일반계고,일반/특목/자율고,일반계고,55.3,44.7,73.1,26.9,73.7,26.3,73.5,26.5,70.6,29.4,77.0,23.0,76.0,24.0
6,학교유형별,고교유형,고교유형,전문계고,특성화고,특성화계고,47.3,52.7,64.4,35.6,74.3,25.7,75.0,25.0,68.6,31.4,75.6,24.4,77.1,22.9
7,지역규모별,지역규모별,지역규모별,대도시,대도시,대도시,53.6,46.4,72.7,27.3,76.8,23.2,77.5,22.5,78.4,21.6,80.6,19.4,79.8,20.2
8,지역규모별,지역규모별,지역규모별,중소도시,중소도시,중소도시,52.5,47.5,67.4,32.6,72.3,27.7,67.3,32.7,70.3,29.7,74.8,25.2,72.5,27.5
9,지역규모별,지역규모별,지역규모별,읍/면,읍/면,읍/면,54.0,46.0,77.5,22.5,75.7,24.3,72.4,27.6,70.7,29.3,77.4,22.6,76.5,23.5
10,가족유형별,가족유형별,가족유형별,양부모가정,양부모가정,양부모가정,54.1,45.9,71.2,28.8,75.0,25.0,72.9,27.1,73.7,26.3,78.0,22.0,76.3,23.7
11,가족유형별,가족유형별,가족유형별,한부모가정,한부모가정,한부모가정,47.4,52.6,68.3,31.7,68.5,31.5,69.2,30.8,73,27,76.4,23.6,71.4,28.6
12,가족유형별,가족유형별,가족유형별,조손가정,조손가정,조손가정,51.7,48.3,75.8,24.2,76.4,23.6,73.9,26.1,79.1,20.9,75.1,24.9,80.0,20.0
13,가족유형별,가족유형별,가족유형별,기타,기타,기타,42.8,57.2,61.7,38.3,69.3,30.7,61.0,39.0,67.5,32.5,59.6,40.4,69.2,30.8
14,경제적수준별,경제적수준별,경제적수준별,상,상,상,57.0,43.0,72.7,27.3,76.9,23.1,74.7,25.3,76.1,23.9,78.5,21.5,77.2,22.8
15,경제적수준별,경제적수준별,경제적수준별,중,중,중,52.7,47.3,68.9,31.1,73.1,26.9,70.2,29.8,70.6,29.4,76.8,23.2,74.4,25.6
16,경제적수준별,경제적수준별,경제적수준별,하,하,하,51.9,48.1,70.5,29.5,72.3,27.7,70.4,29.6,71.6,28.4,75.6,24.4,73.9,26.1

In [32]:
condition =raw.columns.duplicated()

In [33]:
raw=raw.loc[:, ~condition]
raw

,응답자유형별(1),응답자유형별(2),2012 있다(%),2012 없다(%),2013 있다(%),2013 없다(%),2014 있다(%),2014 없다(%),2015 있다(%),2015 없다(%),2016 있다(%),2016 없다(%),2017 있다(%),2017 없다(%),2018 있다(%),2018 없다(%)
0,전체,소계,53.2,46.8,70.9,29.1,74.6,25.4,72.6,27.4,73.6,26.4,77.6,22.4,75.9,24.1
1,성별,남자,52.2,47.8,69.7,30.3,74.4,25.6,72.0,28.0,72.5,27.5,76.3,23.7,74.7,25.3
2,성별,여자,54.4,45.6,72.2,27.8,74.9,25.1,73.2,26.8,74.8,25.2,79.1,20.9,77.2,22.8
3,학교유형별,초등학교,47.6,52.4,67.5,32.5,74.6,25.4,71.3,28.7,76,24,80.3,19.7,76.5,23.5
4,학교유형별,중학교,58.0,42.0,73.1,26.9,75.5,24.5,72.3,27.7,75.4,24.6,76.2,23.8,75.0,25.0
5,학교유형별,일반계고,55.3,44.7,73.1,26.9,73.7,26.3,73.5,26.5,70.6,29.4,77.0,23.0,76.0,24.0
6,학교유형별,전문계고,47.3,52.7,64.4,35.6,74.3,25.7,75.0,25.0,68.6,31.4,75.6,24.4,77.1,22.9
7,지역규모별,대도시,53.6,46.4,72.7,27.3,76.8,23.2,77.5,22.5,78.4,21.6,80.6,19.4,79.8,20.2
8,지역규모별,중소도시,52.5,47.5,67.4,32.6,72.3,27.7,67.3,32.7,70.3,29.7,74.8,25.2,72.5,27.5
9,지역규모별,읍/면,54.0,46.0,77.5,22.5,75.7,24.3,72.4,27.6,70.7,29.3,77.4,22.6,76.5,23.5
10,가족유형별,양부모가정,54.1,45.9,71.2,28.8,75.0,25.0,72.9,27.1,73.7,26.3,78.0,22.0,76.3,23.7
11,가족유형별,한부모가정,47.4,52.6,68.3,31.7,68.5,31.5,69.2,30.8,73,27,76.4,23.6,71.4,28.6
12,가족유형별,조손가정,51.7,48.3,75.8,24.2,76.4,23.6,73.9,26.1,79.1,20.9,75.1,24.9,80.0,20.0
13,가족유형별,기타,42.8,57.2,61.7,38.3,69.3,30.7,61.0,39.0,67.5,32.5,59.6,40.4,69.2,30.8
14,경제적수준별,상,57.0,43.0,72.7,27.3,76.9,23.1,74.7,25.3,76.1,23.9,78.5,21.5,77.2,22.8
15,경제적수준별,중,52.7,47.3,68.9,31.1,73.1,26.9,70.2,29.8,70.6,29.4,76.8,23.2,74.4,25.6
16,경제적수준별,하,51.9,48.1,70.5,29.5,72.3,27.7,70.4,29.6,71.6,28.4,75.6,24.4,73.9,26.1

In [ ]:
# 데이터셋을 분리
# 남/여(sex) >>다날리고 남녀만 남김
# 초등(elementary) >> 중학교/고등학교 날림, ""초등/지역규모""=>중요!!, 초등 / 가정형태 , 초등/경제수준 
# 중등(mid) >> 초등/고등학교 날림
# 고등(high) >> 초등/중등 날림

In [34]:
sex= raw[raw['응답자유형별(1)'] == "성별"]
sex

,응답자유형별(1),응답자유형별(2),2012 있다(%),2012 없다(%),2013 있다(%),2013 없다(%),2014 있다(%),2014 없다(%),2015 있다(%),2015 없다(%),2016 있다(%),2016 없다(%),2017 있다(%),2017 없다(%),2018 있다(%),2018 없다(%)
1,성별,남자,52.2,47.8,69.7,30.3,74.4,25.6,72.0,28.0,72.5,27.5,76.3,23.7,74.7,25.3
2,성별,여자,54.4,45.6,72.2,27.8,74.9,25.1,73.2,26.8,74.8,25.2,79.1,20.9,77.2,22.8

In [35]:
elementary= raw.drop([4,5,6])
elementary=elementary.reset_index(drop=True)
elementary

,응답자유형별(1),응답자유형별(2),2012 있다(%),2012 없다(%),2013 있다(%),2013 없다(%),2014 있다(%),2014 없다(%),2015 있다(%),2015 없다(%),2016 있다(%),2016 없다(%),2017 있다(%),2017 없다(%),2018 있다(%),2018 없다(%)
0,전체,소계,53.2,46.8,70.9,29.1,74.6,25.4,72.6,27.4,73.6,26.4,77.6,22.4,75.9,24.1
1,성별,남자,52.2,47.8,69.7,30.3,74.4,25.6,72.0,28.0,72.5,27.5,76.3,23.7,74.7,25.3
2,성별,여자,54.4,45.6,72.2,27.8,74.9,25.1,73.2,26.8,74.8,25.2,79.1,20.9,77.2,22.8
3,학교유형별,초등학교,47.6,52.4,67.5,32.5,74.6,25.4,71.3,28.7,76,24,80.3,19.7,76.5,23.5
4,지역규모별,대도시,53.6,46.4,72.7,27.3,76.8,23.2,77.5,22.5,78.4,21.6,80.6,19.4,79.8,20.2
5,지역규모별,중소도시,52.5,47.5,67.4,32.6,72.3,27.7,67.3,32.7,70.3,29.7,74.8,25.2,72.5,27.5
6,지역규모별,읍/면,54.0,46.0,77.5,22.5,75.7,24.3,72.4,27.6,70.7,29.3,77.4,22.6,76.5,23.5
7,가족유형별,양부모가정,54.1,45.9,71.2,28.8,75.0,25.0,72.9,27.1,73.7,26.3,78.0,22.0,76.3,23.7
8,가족유형별,한부모가정,47.4,52.6,68.3,31.7,68.5,31.5,69.2,30.8,73,27,76.4,23.6,71.4,28.6
9,가족유형별,조손가정,51.7,48.3,75.8,24.2,76.4,23.6,73.9,26.1,79.1,20.9,75.1,24.9,80.0,20.0
10,가족유형별,기타,42.8,57.2,61.7,38.3,69.3,30.7,61.0,39.0,67.5,32.5,59.6,40.4,69.2,30.8
11,경제적수준별,상,57.0,43.0,72.7,27.3,76.9,23.1,74.7,25.3,76.1,23.9,78.5,21.5,77.2,22.8
12,경제적수준별,중,52.7,47.3,68.9,31.1,73.1,26.9,70.2,29.8,70.6,29.4,76.8,23.2,74.4,25.6
13,경제적수준별,하,51.9,48.1,70.5,29.5,72.3,27.7,70.4,29.6,71.6,28.4,75.6,24.4,73.9,26.1

In [36]:
mid=raw.drop([3,5,6])
mid=mid.reset_index(drop=True)
mid

,응답자유형별(1),응답자유형별(2),2012 있다(%),2012 없다(%),2013 있다(%),2013 없다(%),2014 있다(%),2014 없다(%),2015 있다(%),2015 없다(%),2016 있다(%),2016 없다(%),2017 있다(%),2017 없다(%),2018 있다(%),2018 없다(%)
0,전체,소계,53.2,46.8,70.9,29.1,74.6,25.4,72.6,27.4,73.6,26.4,77.6,22.4,75.9,24.1
1,성별,남자,52.2,47.8,69.7,30.3,74.4,25.6,72.0,28.0,72.5,27.5,76.3,23.7,74.7,25.3
2,성별,여자,54.4,45.6,72.2,27.8,74.9,25.1,73.2,26.8,74.8,25.2,79.1,20.9,77.2,22.8
3,학교유형별,중학교,58.0,42.0,73.1,26.9,75.5,24.5,72.3,27.7,75.4,24.6,76.2,23.8,75.0,25.0
4,지역규모별,대도시,53.6,46.4,72.7,27.3,76.8,23.2,77.5,22.5,78.4,21.6,80.6,19.4,79.8,20.2
5,지역규모별,중소도시,52.5,47.5,67.4,32.6,72.3,27.7,67.3,32.7,70.3,29.7,74.8,25.2,72.5,27.5
6,지역규모별,읍/면,54.0,46.0,77.5,22.5,75.7,24.3,72.4,27.6,70.7,29.3,77.4,22.6,76.5,23.5
7,가족유형별,양부모가정,54.1,45.9,71.2,28.8,75.0,25.0,72.9,27.1,73.7,26.3,78.0,22.0,76.3,23.7
8,가족유형별,한부모가정,47.4,52.6,68.3,31.7,68.5,31.5,69.2,30.8,73,27,76.4,23.6,71.4,28.6
9,가족유형별,조손가정,51.7,48.3,75.8,24.2,76.4,23.6,73.9,26.1,79.1,20.9,75.1,24.9,80.0,20.0
10,가족유형별,기타,42.8,57.2,61.7,38.3,69.3,30.7,61.0,39.0,67.5,32.5,59.6,40.4,69.2,30.8
11,경제적수준별,상,57.0,43.0,72.7,27.3,76.9,23.1,74.7,25.3,76.1,23.9,78.5,21.5,77.2,22.8
12,경제적수준별,중,52.7,47.3,68.9,31.1,73.1,26.9,70.2,29.8,70.6,29.4,76.8,23.2,74.4,25.6
13,경제적수준별,하,51.9,48.1,70.5,29.5,72.3,27.7,70.4,29.6,71.6,28.4,75.6,24.4,73.9,26.1

In [37]:
high=raw.drop([3,4])
high=high.reset_index(drop=True)
high

,응답자유형별(1),응답자유형별(2),2012 있다(%),2012 없다(%),2013 있다(%),2013 없다(%),2014 있다(%),2014 없다(%),2015 있다(%),2015 없다(%),2016 있다(%),2016 없다(%),2017 있다(%),2017 없다(%),2018 있다(%),2018 없다(%)
0,전체,소계,53.2,46.8,70.9,29.1,74.6,25.4,72.6,27.4,73.6,26.4,77.6,22.4,75.9,24.1
1,성별,남자,52.2,47.8,69.7,30.3,74.4,25.6,72.0,28.0,72.5,27.5,76.3,23.7,74.7,25.3
2,성별,여자,54.4,45.6,72.2,27.8,74.9,25.1,73.2,26.8,74.8,25.2,79.1,20.9,77.2,22.8
3,학교유형별,일반계고,55.3,44.7,73.1,26.9,73.7,26.3,73.5,26.5,70.6,29.4,77.0,23.0,76.0,24.0
4,학교유형별,전문계고,47.3,52.7,64.4,35.6,74.3,25.7,75.0,25.0,68.6,31.4,75.6,24.4,77.1,22.9
5,지역규모별,대도시,53.6,46.4,72.7,27.3,76.8,23.2,77.5,22.5,78.4,21.6,80.6,19.4,79.8,20.2
6,지역규모별,중소도시,52.5,47.5,67.4,32.6,72.3,27.7,67.3,32.7,70.3,29.7,74.8,25.2,72.5,27.5
7,지역규모별,읍/면,54.0,46.0,77.5,22.5,75.7,24.3,72.4,27.6,70.7,29.3,77.4,22.6,76.5,23.5
8,가족유형별,양부모가정,54.1,45.9,71.2,28.8,75.0,25.0,72.9,27.1,73.7,26.3,78.0,22.0,76.3,23.7
9,가족유형별,한부모가정,47.4,52.6,68.3,31.7,68.5,31.5,69.2,30.8,73,27,76.4,23.6,71.4,28.6
10,가족유형별,조손가정,51.7,48.3,75.8,24.2,76.4,23.6,73.9,26.1,79.1,20.9,75.1,24.9,80.0,20.0
11,가족유형별,기타,42.8,57.2,61.7,38.3,69.3,30.7,61.0,39.0,67.5,32.5,59.6,40.4,69.2,30.8
12,경제적수준별,상,57.0,43.0,72.7,27.3,76.9,23.1,74.7,25.3,76.1,23.9,78.5,21.5,77.2,22.8
13,경제적수준별,중,52.7,47.3,68.9,31.1,73.1,26.9,70.2,29.8,70.6,29.4,76.8,23.2,74.4,25.6
14,경제적수준별,하,51.9,48.1,70.5,29.5,72.3,27.7,70.4,29.6,71.6,28.4,75.6,24.4,73.9,26.1